### ISSUE TITLE
Cannot populate database

### ISSUE THREAD

**Issue by adocampo** [linuxserver/docker-fleet#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When running `docker-compose up -d` it should populate the database.

## Current Behavior
It fails with the following error.
```
fleet    | Caused by: java.sql.SQLException: (conn=2483590) Cannot load from mysql.proc. The table is probably corrupted
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
fleet    |      at org.mariadb.jdbc.client.result.Result.readNext(Result.java:162)
fleet    |      at org.mariadb.jdbc.client.result.CompleteResult.<init>(CompleteResult.java:69)
fleet    |      at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:252)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:824)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:763)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:682)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:625)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:285)
fleet    |      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
fleet    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
fleet    |      at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:104)
fleet    |      at org.flywaydb.core.internal.database.mysql.MySQLSchema.doEmpty(MySQLSchema.java:46)
fleet    |      at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:66)
fleet    |      ... 11 more
fleet    | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
fleet    | WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```

## Steps to Reproduce

1. Download `docker-compose.yml`
2. Edit the database settings
3. Create a database and a user with permissions to that database matching the one specified on `docker-compose.yml`
4. Execute ` docker-compose up -d`

## Environment
**OS:** Arch linux (KVM VM)
**CPU architecture:** x86_64
**How docker service was installed:** through package manager (pacman)

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`
`docker-compose up - d fleet`
## Docker logs

```
root@docker:~/fleet# docker-compose up 
Creating network "fleet_default" with the default driver
Creating fleet ... done
Attaching to fleet
fleet    | [custom-init] No custom services found, skipping...
fleet    | s6-rc: info: service s6rc-oneshot-runner: starting
fleet    | s6-rc: info: service s6rc-oneshot-runner successfully started
fleet    | s6-rc: info: service fix-attrs: starting
fleet    | s6-rc: info: service 00-legacy: starting
fleet    | s6-rc: info: service 00-legacy successfully started
fleet    | s6-rc: info: service fix-attrs successfully started
fleet    | s6-rc: info: service legacy-cont-init: starting
fleet    | cont-init: info: running /etc/cont-init.d/01-envfile
fleet    | cont-init: info: /etc/cont-init.d/01-envfile exited 0
fleet    | cont-init: info: running /etc/cont-init.d/01-migrations
fleet    | [migrations] started
fleet    | [migrations] no migrations found
fleet    | cont-init: info: /etc/cont-init.d/01-migrations exited 0
fleet    | cont-init: info: running /etc/cont-init.d/10-adduser
fleet    | 
fleet    | -------------------------------------
fleet    |           _         ()
fleet    |          | |  ___   _    __
fleet    |          | | / __| | |  /  \
fleet    |          | | \__ \ | | | () |
fleet    |          |_| |___/ |_|  \__/
fleet    | 
fleet    | 
fleet    | Brought to you by linuxserver.io
fleet    | -------------------------------------
fleet    | 
fleet    | To support LSIO projects visit:
fleet    | https://www.linuxserver.io/donate/
fleet    | -------------------------------------
fleet    | GID/UID
fleet    | -------------------------------------
fleet    | 
fleet    | User uid:    1000
fleet    | User gid:    1000
fleet    | -------------------------------------
fleet    | 
fleet    | cont-init: info: /etc/cont-init.d/10-adduser exited 0
fleet    | cont-init: info: running /etc/cont-init.d/19-armless
fleet    | cont-init: info: /etc/cont-init.d/19-armless exited 0
fleet    | cont-init: info: running /etc/cont-init.d/30-config
fleet    | cont-init: info: /etc/cont-init.d/30-config exited 0
fleet    | cont-init: info: running /etc/cont-init.d/99-custom-files
fleet    | [custom-init] No custom files found, skipping...
fleet    | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
fleet    | s6-rc: info: service legacy-cont-init successfully started
fleet    | s6-rc: info: service init-mods: starting
fleet    | s6-rc: info: service init-mods successfully started
fleet    | s6-rc: info: service init-mods-package-install: starting
fleet    | s6-rc: info: service init-mods-package-install successfully started
fleet    | s6-rc: info: service init-mods-end: starting
fleet    | s6-rc: info: service init-mods-end successfully started
fleet    | s6-rc: info: service init-services: starting
fleet    | s6-rc: info: service init-services successfully started
fleet    | s6-rc: info: service legacy-services: starting
fleet    | services-up: info: copying legacy longrun fleet (no readiness notification)
fleet    | s6-rc: info: service legacy-services successfully started
fleet    | s6-rc: info: service 99-ci-service-check: starting
fleet    | [ls.io-init] done.
fleet    | s6-rc: info: service 99-ci-service-check successfully started
fleet    | WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
fleet    | Exception in thread "main" java.lang.RuntimeException: Unable to start application because the database has gone out of sync.
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.migrate(DatabaseVersion.java:61)
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.<init>(DatabaseVersion.java:40)
fleet    |      at io.linuxserver.fleet.core.db.DefaultDatabaseProvider.<init>(DefaultDatabaseProvider.java:29)
fleet    |      at io.linuxserver.fleet.core.AbstractAppController.<init>(AbstractAppController.java:41)
fleet    |      at io.linuxserver.fleet.core.FleetAppController.<init>(FleetAppController.java:58)
fleet    |      at io.linuxserver.fleet.core.FleetAppController.instance(FleetAppController.java:77)
fleet    |      at io.linuxserver.fleet.core.Main.main(Main.java:23)
fleet    | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to check whether schema `fleet` is empty
fleet    | -----------------------------------------------
fleet    | SQL State  : HY000
fleet    | Error Code : 1728
fleet    | Message    : (conn=8) Cannot load from mysql.proc. The table is probably corrupted
fleet    | 
fleet    |      at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:68)
fleet    |      at org.flywaydb.core.Flyway$1.execute(Flyway.java:138)
fleet    |      at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
fleet    |      at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214)
fleet    |      at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.migrate(DatabaseVersion.java:56)
fleet    |      ... 6 more
fleet    | Caused by: java.sql.SQLException: (conn=8) Cannot load from mysql.proc. The table is probably corrupted
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
fleet    |      at org.mariadb.jdbc.client.result.Result.readNext(Result.java:162)
fleet    |      at org.mariadb.jdbc.client.result.CompleteResult.<init>(CompleteResult.java:69)
fleet    |      at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:252)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:824)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:763)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:682)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:625)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:285)
fleet    |      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
fleet    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
fleet    |      at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:104)
fleet    |      at org.flywaydb.core.internal.database.mysql.MySQLSchema.doEmpty(MySQLSchema.java:46)
fleet    |      at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:66)
fleet    |      ... 11 more
fleet    | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
fleet    | WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
fleet    | Exception in thread "main" java.lang.RuntimeException: Unable to start application because the database has gone out of sync.
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.migrate(DatabaseVersion.java:61)
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.<init>(DatabaseVersion.java:40)
fleet    |      at io.linuxserver.fleet.core.db.DefaultDatabaseProvider.<init>(DefaultDatabaseProvider.java:29)
fleet    |      at io.linuxserver.fleet.core.AbstractAppController.<init>(AbstractAppController.java:41)
fleet    |      at io.linuxserver.fleet.core.FleetAppController.<init>(FleetAppController.java:58)
fleet    |      at io.linuxserver.fleet.core.FleetAppController.instance(FleetAppController.java:77)
fleet    |      at io.linuxserver.fleet.core.Main.main(Main.java:23)
fleet    | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to check whether schema `fleet` is empty
fleet    | -----------------------------------------------
fleet    | SQL State  : HY000
fleet    | Error Code : 1728
fleet    | Message    : (conn=13) Cannot load from mysql.proc. The table is probably corrupted
fleet    | 
fleet    |      at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:68)
fleet    |      at org.flywaydb.core.Flyway$1.execute(Flyway.java:138)
fleet    |      at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
fleet    |      at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214)
fleet    |      at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
fleet    |      at io.linuxserver.fleet.db.migration.DatabaseVersion.migrate(DatabaseVersion.java:56)
fleet    |      ... 6 more
fleet    | Caused by: java.sql.SQLException: (conn=13) Cannot load from mysql.proc. The table is probably corrupted
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
fleet    |      at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
fleet    |      at org.mariadb.jdbc.client.result.Result.readNext(Result.java:162)
fleet    |      at org.mariadb.jdbc.client.result.CompleteResult.<init>(CompleteResult.java:69)
fleet    |      at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:252)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:824)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:763)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:682)
fleet    |      at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:625)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
fleet    |      at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:285)
fleet    |      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
fleet    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
fleet    |      at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:104)
fleet    |      at org.flywaydb.core.internal.database.mysql.MySQLSchema.doEmpty(MySQLSchema.java:46)
fleet    |      at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:66)
fleet    |      ... 11 more
fleet    | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
^CGracefully stopping... (press Ctrl+C again to force)
Stopping fleet ... done
```

**Comment by aptalca** [comment]
Revert mariadb back a version. Fleet is having issues with the latest

**Comment by adocampo** [comment]
Which version should I need?  I'm not using the latest (minor) version.
```
root@sql01:~# mysql --version
mysql  Ver 15.1 Distrib 10.6.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

BTW, my mariadb instance is **NOT** a docker container, but a regular VM

**Comment by aptalca** [comment]
@adocampo I just realized that the latest fleet is indeed working with the latest mariadb, but, after an upgrade of mariadb, you need to run `mariadb-upgrade -u root -p<yourpassword>` and then fleet should work fine.

**Comment by adocampo** [comment]
Well, that command did the job, indeed.
Thank you very much!
